# Generated by Django 3.0.6 on 2020-05-31 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='preco',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produto',
            name='titulo',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
